### ISSUE TITLE
I have problem with message.reply(welcomeMsg) on iOS when app in background and run as profile or release mode. Plz help to check and improve on this!

### ISSUE THREAD

**Issue by sophanitkong** [DinoLeung/TeleDart#250] opened 2023-05-16 07:19 UTC
## To Reproduce
Snippet to reproduce the behavior:
```dart
// Place snippet here
```

**Comment by DinoLeung** [comment] 2023-05-19 06:10
@sophanitkong can you provide sufficient info such as code snippet, expected behaviour and actual behaviour to this issue? Not to mention this library is not intended to support flutter. I will be closing this issue next week if no further information is give.

**Comment by sophanitkong** [comment] 2023-05-19 06:21
1. on iOS: 
teledart
      ..onCommand("start").listen((message) {
        /* 
            This block work only on Android
         */
        message.reply(successMsg);
        setValueChatAttribute(message);
        showSuccessLinkedTelegram();
      })
      ..onCommand("showmyid").listen((message) {
        message.reply("Your Telegram Group ID: `$chatId`");
      });
Code in this block is not execute. In android it execute as expected.
2. on iOS:
teledart
      ..onMessage()
          .listen((message) {
        message.reply(successMsg);
      })
This code execute only in Debug mode, but if I run it on Profile or Release mode is not work when app is in background.

**Comment by DinoLeung** [comment] 2023-05-22 02:05
@sophanitkong which updates fetching method are you using?

**Comment by sophanitkong** [comment] 2023-05-22 02:12
I don't understand your question since the code I have added above is what I am using, I don't use any update methods. Moreover, according to document provided by library is I don't see the suggestion of using update methods.

**Comment by sophanitkong** [comment] 2023-05-31 08:44
@DinoLeung Updated, You should update the document on this library with iOS configuration since iOS need to add capability background modes. If not it is only work in Android.

**Closed** 2023-05-31 08:45 UTC
Labels: bug
